# Generated by Django 4.2.6 on 2023-10-21 19:54

import datetime
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_subject_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
